### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 0x241F31** [MrFoxPro/solid-nativescript-experiments#1]
- [ ] Improve renderer, handle complex cases on inserting/removing children
- [ ] Add tests
- [ ] Add navigation tools
- [ ] Publish to NPM
- [ ] Improve HMR experience

**Comment by svicalifornia** [comment]
@MrFoxPro Has there been any progress on this? Can I help?
